# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IPC.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Ventana_(object):
    def setupUi(self, Ventana_):
        Ventana_.setObjectName("Ventana_")
        Ventana_.resize(379, 323)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 238, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 246, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 119, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 159, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 238, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 246, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 238, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 246, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 119, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 159, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 238, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 246, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 119, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 238, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 246, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 119, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 159, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 119, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 119, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 238, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 238, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 238, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        Ventana_.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ipc.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ventana_.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(Ventana_)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cajaAnos = QtWidgets.QGroupBox(Ventana_)
        self.cajaAnos.setObjectName("cajaAnos")
        self.gridLayout = QtWidgets.QGridLayout(self.cajaAnos)
        self.gridLayout.setObjectName("gridLayout")
        self.inputAno2 = QtWidgets.QRadioButton(self.cajaAnos)
        self.inputAno2.setCheckable(True)
        self.inputAno2.setChecked(False)
        self.inputAno2.setAutoRepeat(True)
        self.inputAno2.setObjectName("inputAno2")
        self.gridLayout.addWidget(self.inputAno2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.cajaAnos, 0, 0, 1, 1)
        self.cajaBienes = QtWidgets.QGroupBox(Ventana_)
        self.cajaBienes.setObjectName("cajaBienes")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.cajaBienes)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.inputBienes4 = QtWidgets.QRadioButton(self.cajaBienes)
        self.inputBienes4.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.inputBienes4.setFont(font)
        self.inputBienes4.setWhatsThis("")
        self.inputBienes4.setObjectName("inputBienes4")
        self.gridLayout_2.addWidget(self.inputBienes4, 1, 0, 1, 1)
        self.inputBienes3 = QtWidgets.QRadioButton(self.cajaBienes)
        self.inputBienes3.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.inputBienes3.setFont(font)
        self.inputBienes3.setWhatsThis("")
        self.inputBienes3.setObjectName("inputBienes3")
        self.gridLayout_2.addWidget(self.inputBienes3, 2, 0, 1, 1)
        self.inputBienes2 = QtWidgets.QRadioButton(self.cajaBienes)
        self.inputBienes2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.inputBienes2.setFont(font)
        self.inputBienes2.setWhatsThis("")
        self.inputBienes2.setObjectName("inputBienes2")
        self.gridLayout_2.addWidget(self.inputBienes2, 3, 0, 1, 1)
        self.inputBienes5 = QtWidgets.QRadioButton(self.cajaBienes)
        self.inputBienes5.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.inputBienes5.setFont(font)
        self.inputBienes5.setObjectName("inputBienes5")
        self.gridLayout_2.addWidget(self.inputBienes5, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.cajaBienes, 0, 1, 2, 1)
        self.cajaPorcentajes = QtWidgets.QGroupBox(Ventana_)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cajaPorcentajes.setFont(font)
        self.cajaPorcentajes.setObjectName("cajaPorcentajes")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.cajaPorcentajes)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.inputPorcentaje4 = QtWidgets.QSpinBox(self.cajaPorcentajes)
        self.inputPorcentaje4.setEnabled(False)
        self.inputPorcentaje4.setWhatsThis("")
        self.inputPorcentaje4.setWrapping(True)
        self.inputPorcentaje4.setAccelerated(True)
        self.inputPorcentaje4.setMinimum(1)
        self.inputPorcentaje4.setMaximum(100)
        self.inputPorcentaje4.setProperty("value", 1)
        self.inputPorcentaje4.setObjectName("inputPorcentaje4")
        self.gridLayout_7.addWidget(self.inputPorcentaje4, 3, 1, 1, 1)
        self.inputPorcentaje3 = QtWidgets.QSpinBox(self.cajaPorcentajes)
        self.inputPorcentaje3.setEnabled(False)
        self.inputPorcentaje3.setWhatsThis("")
        self.inputPorcentaje3.setWrapping(True)
        self.inputPorcentaje3.setAccelerated(True)
        self.inputPorcentaje3.setProperty("showGroupSeparator", False)
        self.inputPorcentaje3.setPrefix("")
        self.inputPorcentaje3.setMinimum(1)
        self.inputPorcentaje3.setMaximum(100)
        self.inputPorcentaje3.setProperty("value", 1)
        self.inputPorcentaje3.setObjectName("inputPorcentaje3")
        self.gridLayout_7.addWidget(self.inputPorcentaje3, 2, 1, 1, 1)
        self.printPorcentaje3 = QtWidgets.QLabel(self.cajaPorcentajes)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.printPorcentaje3.setFont(font)
        self.printPorcentaje3.setObjectName("printPorcentaje3")
        self.gridLayout_7.addWidget(self.printPorcentaje3, 2, 0, 1, 1)
        self.printPorcentaje4 = QtWidgets.QLabel(self.cajaPorcentajes)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.printPorcentaje4.setFont(font)
        self.printPorcentaje4.setObjectName("printPorcentaje4")
        self.gridLayout_7.addWidget(self.printPorcentaje4, 3, 0, 1, 1)
        self.printPorcentaje1 = QtWidgets.QLabel(self.cajaPorcentajes)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.printPorcentaje1.setFont(font)
        self.printPorcentaje1.setObjectName("printPorcentaje1")
        self.gridLayout_7.addWidget(self.printPorcentaje1, 0, 0, 1, 1)
        self.inputPorcentaje1 = QtWidgets.QSpinBox(self.cajaPorcentajes)
        self.inputPorcentaje1.setEnabled(False)
        self.inputPorcentaje1.setWhatsThis("")
        self.inputPorcentaje1.setWrapping(True)
        self.inputPorcentaje1.setAccelerated(True)
        self.inputPorcentaje1.setMinimum(1)
        self.inputPorcentaje1.setMaximum(100)
        self.inputPorcentaje1.setProperty("value", 1)
        self.inputPorcentaje1.setDisplayIntegerBase(10)
        self.inputPorcentaje1.setObjectName("inputPorcentaje1")
        self.gridLayout_7.addWidget(self.inputPorcentaje1, 0, 1, 1, 1)
        self.printPorcentaje2 = QtWidgets.QLabel(self.cajaPorcentajes)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.printPorcentaje2.setFont(font)
        self.printPorcentaje2.setObjectName("printPorcentaje2")
        self.gridLayout_7.addWidget(self.printPorcentaje2, 1, 0, 1, 1)
        self.inputPorcentaje2 = QtWidgets.QSpinBox(self.cajaPorcentajes)
        self.inputPorcentaje2.setEnabled(False)
        self.inputPorcentaje2.setWhatsThis("")
        self.inputPorcentaje2.setWrapping(True)
        self.inputPorcentaje2.setAccelerated(True)
        self.inputPorcentaje2.setPrefix("")
        self.inputPorcentaje2.setMinimum(1)
        self.inputPorcentaje2.setMaximum(100)
        self.inputPorcentaje2.setProperty("value", 1)
        self.inputPorcentaje2.setObjectName("inputPorcentaje2")
        self.gridLayout_7.addWidget(self.inputPorcentaje2, 1, 1, 1, 1)
        self.printPorcentaje5 = QtWidgets.QLabel(self.cajaPorcentajes)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.printPorcentaje5.setFont(font)
        self.printPorcentaje5.setObjectName("printPorcentaje5")
        self.gridLayout_7.addWidget(self.printPorcentaje5, 4, 0, 1, 1)
        self.inputPorcentaje5 = QtWidgets.QSpinBox(self.cajaPorcentajes)
        self.inputPorcentaje5.setEnabled(False)
        self.inputPorcentaje5.setWhatsThis("")
        self.inputPorcentaje5.setWrapping(True)
        self.inputPorcentaje5.setAccelerated(True)
        self.inputPorcentaje5.setMinimum(1)
        self.inputPorcentaje5.setMaximum(100)
        self.inputPorcentaje5.setProperty("value", 1)
        self.inputPorcentaje5.setObjectName("inputPorcentaje5")
        self.gridLayout_7.addWidget(self.inputPorcentaje5, 4, 1, 1, 1)
        self.gridLayout_3.addWidget(self.cajaPorcentajes, 0, 2, 2, 1)
        self.cajaGrafico = QtWidgets.QGroupBox(Ventana_)
        self.cajaGrafico.setObjectName("cajaGrafico")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.cajaGrafico)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.botonGrafico = QtWidgets.QPushButton(self.cajaGrafico)
        self.botonGrafico.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.botonGrafico.setFont(font)
        self.botonGrafico.setWhatsThis("")
        self.botonGrafico.setObjectName("botonGrafico")
        self.gridLayout_5.addWidget(self.botonGrafico, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.cajaGrafico, 1, 0, 1, 1)
        self.cajaDatos = QtWidgets.QGroupBox(Ventana_)
        self.cajaDatos.setObjectName("cajaDatos")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.cajaDatos)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.inputAno22 = QtWidgets.QSpinBox(self.cajaDatos)
        self.inputAno22.setEnabled(False)
        self.inputAno22.setWhatsThis("")
        self.inputAno22.setWrapping(True)
        self.inputAno22.setAccelerated(True)
        self.inputAno22.setMaximum(500)
        self.inputAno22.setProperty("value", 1)
        self.inputAno22.setObjectName("inputAno22")
        self.gridLayout_4.addWidget(self.inputAno22, 1, 5, 1, 1)
        self.printAno12 = QtWidgets.QLabel(self.cajaDatos)
        self.printAno12.setObjectName("printAno12")
        self.gridLayout_4.addWidget(self.printAno12, 1, 2, 1, 1)
        self.inputAno02 = QtWidgets.QSpinBox(self.cajaDatos)
        self.inputAno02.setEnabled(False)
        self.inputAno02.setWhatsThis("")
        self.inputAno02.setWrapping(True)
        self.inputAno02.setAccelerated(True)
        self.inputAno02.setMinimum(1)
        self.inputAno02.setMaximum(500)
        self.inputAno02.setProperty("value", 1)
        self.inputAno02.setObjectName("inputAno02")
        self.gridLayout_4.addWidget(self.inputAno02, 1, 1, 1, 1)
        self.inputAno12 = QtWidgets.QSpinBox(self.cajaDatos)
        self.inputAno12.setEnabled(False)
        self.inputAno12.setWhatsThis("")
        self.inputAno12.setWrapping(True)
        self.inputAno12.setAccelerated(True)
        self.inputAno12.setMinimum(1)
        self.inputAno12.setMaximum(500)
        self.inputAno12.setProperty("value", 1)
        self.inputAno12.setObjectName("inputAno12")
        self.gridLayout_4.addWidget(self.inputAno12, 1, 3, 1, 1)
        self.printAno22 = QtWidgets.QLabel(self.cajaDatos)
        self.printAno22.setObjectName("printAno22")
        self.gridLayout_4.addWidget(self.printAno22, 1, 4, 1, 1)
        self.inputAno03 = QtWidgets.QSpinBox(self.cajaDatos)
        self.inputAno03.setEnabled(False)
        self.inputAno03.setWhatsThis("")
        self.inputAno03.setWrapping(True)
        self.inputAno03.setAccelerated(True)
        self.inputAno03.setMinimum(1)
        self.inputAno03.setMaximum(500)
        self.inputAno03.setProperty("value", 1)
        self.inputAno03.setObjectName("inputAno03")
        self.gridLayout_4.addWidget(self.inputAno03, 2, 1, 1, 1)
        self.printAno03 = QtWidgets.QLabel(self.cajaDatos)
        self.printAno03.setObjectName("printAno03")
        self.gridLayout_4.addWidget(self.printAno03, 2, 0, 1, 1)
        self.inputAno23 = QtWidgets.QSpinBox(self.cajaDatos)
        self.inputAno23.setEnabled(False)
        self.inputAno23.setWhatsThis("")
        self.inputAno23.setWrapping(True)
        self.inputAno23.setAccelerated(True)
        self.inputAno23.setMaximum(500)
        self.inputAno23.setProperty("value", 1)
        self.inputAno23.setObjectName("inputAno23")
        self.gridLayout_4.addWidget(self.inputAno23, 2, 5, 1, 1)
        self.printAno14 = QtWidgets.QLabel(self.cajaDatos)
        self.printAno14.setObjectName("printAno14")
        self.gridLayout_4.addWidget(self.printAno14, 3, 2, 1, 1)
        self.inputAno04 = QtWidgets.QSpinBox(self.cajaDatos)
        self.inputAno04.setEnabled(False)
        self.inputAno04.setWhatsThis("")
        self.inputAno04.setWrapping(True)
        self.inputAno04.setAccelerated(True)
        self.inputAno04.setMinimum(1)
        self.inputAno04.setMaximum(500)
        self.inputAno04.setProperty("value", 1)
        self.inputAno04.setObjectName("inputAno04")
        self.gridLayout_4.addWidget(self.inputAno04, 3, 1, 1, 1)
        self.printAno04 = QtWidgets.QLabel(self.cajaDatos)
        self.printAno04.setObjectName("printAno04")
        self.gridLayout_4.addWidget(self.printAno04, 3, 0, 1, 1)
        self.inputAno13 = QtWidgets.QSpinBox(self.cajaDatos)
        self.inputAno13.setEnabled(False)
        self.inputAno13.setWhatsThis("")
        self.inputAno13.setWrapping(True)
        self.inputAno13.setAccelerated(True)
        self.inputAno13.setMinimum(1)
        self.inputAno13.setMaximum(500)
        self.inputAno13.setProperty("value", 1)
        self.inputAno13.setObjectName("inputAno13")
        self.gridLayout_4.addWidget(self.inputAno13, 2, 3, 1, 1)
        self.printAno13 = QtWidgets.QLabel(self.cajaDatos)
        self.printAno13.setObjectName("printAno13")
        self.gridLayout_4.addWidget(self.printAno13, 2, 2, 1, 1)
        self.printAno23 = QtWidgets.QLabel(self.cajaDatos)
        self.printAno23.setObjectName("printAno23")
        self.gridLayout_4.addWidget(self.printAno23, 2, 4, 1, 1)
        self.inputAno01 = QtWidgets.QSpinBox(self.cajaDatos)
        self.inputAno01.setEnabled(False)
        self.inputAno01.setWhatsThis("")
        self.inputAno01.setWrapping(True)
        self.inputAno01.setAccelerated(True)
        self.inputAno01.setMinimum(1)
        self.inputAno01.setMaximum(500)
        self.inputAno01.setProperty("value", 1)
        self.inputAno01.setObjectName("inputAno01")
        self.gridLayout_4.addWidget(self.inputAno01, 0, 1, 1, 1)
        self.printAno11 = QtWidgets.QLabel(self.cajaDatos)
        self.printAno11.setObjectName("printAno11")
        self.gridLayout_4.addWidget(self.printAno11, 0, 2, 1, 1)
        self.inputAno11 = QtWidgets.QSpinBox(self.cajaDatos)
        self.inputAno11.setEnabled(False)
        self.inputAno11.setWhatsThis("")
        self.inputAno11.setWrapping(True)
        self.inputAno11.setAccelerated(True)
        self.inputAno11.setMinimum(1)
        self.inputAno11.setMaximum(500)
        self.inputAno11.setProperty("value", 1)
        self.inputAno11.setObjectName("inputAno11")
        self.gridLayout_4.addWidget(self.inputAno11, 0, 3, 1, 1)
        self.printAno21 = QtWidgets.QLabel(self.cajaDatos)
        self.printAno21.setObjectName("printAno21")
        self.gridLayout_4.addWidget(self.printAno21, 0, 4, 1, 1)
        self.printAno01 = QtWidgets.QLabel(self.cajaDatos)
        self.printAno01.setObjectName("printAno01")
        self.gridLayout_4.addWidget(self.printAno01, 0, 0, 1, 1)
        self.inputAno21 = QtWidgets.QSpinBox(self.cajaDatos)
        self.inputAno21.setEnabled(False)
        self.inputAno21.setWhatsThis("")
        self.inputAno21.setWrapping(True)
        self.inputAno21.setAccelerated(True)
        self.inputAno21.setMinimum(1)
        self.inputAno21.setMaximum(500)
        self.inputAno21.setProperty("value", 1)
        self.inputAno21.setObjectName("inputAno21")
        self.gridLayout_4.addWidget(self.inputAno21, 0, 5, 1, 1)
        self.printAno02 = QtWidgets.QLabel(self.cajaDatos)
        self.printAno02.setObjectName("printAno02")
        self.gridLayout_4.addWidget(self.printAno02, 1, 0, 1, 1)
        self.inputAno24 = QtWidgets.QSpinBox(self.cajaDatos)
        self.inputAno24.setEnabled(False)
        self.inputAno24.setWhatsThis("")
        self.inputAno24.setWrapping(True)
        self.inputAno24.setAccelerated(True)
        self.inputAno24.setMaximum(500)
        self.inputAno24.setProperty("value", 1)
        self.inputAno24.setObjectName("inputAno24")
        self.gridLayout_4.addWidget(self.inputAno24, 3, 5, 1, 1)
        self.printAno24 = QtWidgets.QLabel(self.cajaDatos)
        self.printAno24.setObjectName("printAno24")
        self.gridLayout_4.addWidget(self.printAno24, 3, 4, 1, 1)
        self.inputAno14 = QtWidgets.QSpinBox(self.cajaDatos)
        self.inputAno14.setEnabled(False)
        self.inputAno14.setWhatsThis("")
        self.inputAno14.setWrapping(True)
        self.inputAno14.setAccelerated(True)
        self.inputAno14.setMinimum(1)
        self.inputAno14.setMaximum(500)
        self.inputAno14.setProperty("value", 1)
        self.inputAno14.setObjectName("inputAno14")
        self.gridLayout_4.addWidget(self.inputAno14, 3, 3, 1, 1)
        self.printAno05 = QtWidgets.QLabel(self.cajaDatos)
        self.printAno05.setObjectName("printAno05")
        self.gridLayout_4.addWidget(self.printAno05, 4, 0, 1, 1)
        self.inputAno05 = QtWidgets.QSpinBox(self.cajaDatos)
        self.inputAno05.setEnabled(False)
        self.inputAno05.setWhatsThis("")
        self.inputAno05.setWrapping(True)
        self.inputAno05.setAccelerated(True)
        self.inputAno05.setMinimum(1)
        self.inputAno05.setMaximum(500)
        self.inputAno05.setProperty("value", 1)
        self.inputAno05.setObjectName("inputAno05")
        self.gridLayout_4.addWidget(self.inputAno05, 4, 1, 1, 1)
        self.printAno15 = QtWidgets.QLabel(self.cajaDatos)
        self.printAno15.setObjectName("printAno15")
        self.gridLayout_4.addWidget(self.printAno15, 4, 2, 1, 1)
        self.inputAno15 = QtWidgets.QSpinBox(self.cajaDatos)
        self.inputAno15.setEnabled(False)
        self.inputAno15.setWhatsThis("")
        self.inputAno15.setWrapping(True)
        self.inputAno15.setAccelerated(True)
        self.inputAno15.setMinimum(1)
        self.inputAno15.setMaximum(500)
        self.inputAno15.setProperty("value", 1)
        self.inputAno15.setObjectName("inputAno15")
        self.gridLayout_4.addWidget(self.inputAno15, 4, 3, 1, 1)
        self.printAno25 = QtWidgets.QLabel(self.cajaDatos)
        self.printAno25.setObjectName("printAno25")
        self.gridLayout_4.addWidget(self.printAno25, 4, 4, 1, 1)
        self.inputAno25 = QtWidgets.QSpinBox(self.cajaDatos)
        self.inputAno25.setEnabled(False)
        self.inputAno25.setWhatsThis("")
        self.inputAno25.setWrapping(True)
        self.inputAno25.setAccelerated(True)
        self.inputAno25.setMaximum(500)
        self.inputAno25.setProperty("value", 1)
        self.inputAno25.setObjectName("inputAno25")
        self.gridLayout_4.addWidget(self.inputAno25, 4, 5, 1, 1)
        self.gridLayout_3.addWidget(self.cajaDatos, 2, 0, 1, 3)
        self.widget = QtWidgets.QWidget(Ventana_)
        self.widget.setWhatsThis("")
        self.widget.setObjectName("widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 3, 2, 1, 1)
        self.printPorcentaje3.setBuddy(self.inputPorcentaje3)
        self.printPorcentaje4.setBuddy(self.inputPorcentaje4)
        self.printPorcentaje1.setBuddy(self.inputPorcentaje1)
        self.printPorcentaje2.setBuddy(self.inputPorcentaje2)
        self.printPorcentaje5.setBuddy(self.inputPorcentaje4)
        self.printAno12.setBuddy(self.inputAno12)
        self.printAno22.setBuddy(self.inputAno22)
        self.printAno03.setBuddy(self.inputAno03)
        self.printAno14.setBuddy(self.inputAno14)
        self.printAno04.setBuddy(self.inputAno04)
        self.printAno13.setBuddy(self.inputAno13)
        self.printAno23.setBuddy(self.inputAno23)
        self.printAno11.setBuddy(self.inputAno11)
        self.printAno21.setBuddy(self.inputAno21)
        self.printAno01.setBuddy(self.inputAno01)
        self.printAno02.setBuddy(self.inputAno02)
        self.printAno24.setBuddy(self.inputAno24)
        self.printAno05.setBuddy(self.inputAno04)
        self.printAno15.setBuddy(self.inputAno14)
        self.printAno25.setBuddy(self.inputAno24)

        self.retranslateUi(Ventana_)
        QtCore.QMetaObject.connectSlotsByName(Ventana_)
        Ventana_.setTabOrder(self.inputAno2, self.inputBienes4)
        Ventana_.setTabOrder(self.inputBienes4, self.inputBienes3)
        Ventana_.setTabOrder(self.inputBienes3, self.inputBienes2)
        Ventana_.setTabOrder(self.inputBienes2, self.inputPorcentaje1)
        Ventana_.setTabOrder(self.inputPorcentaje1, self.inputPorcentaje2)
        Ventana_.setTabOrder(self.inputPorcentaje2, self.inputPorcentaje3)
        Ventana_.setTabOrder(self.inputPorcentaje3, self.inputPorcentaje4)
        Ventana_.setTabOrder(self.inputPorcentaje4, self.inputAno01)
        Ventana_.setTabOrder(self.inputAno01, self.inputAno02)
        Ventana_.setTabOrder(self.inputAno02, self.inputAno03)
        Ventana_.setTabOrder(self.inputAno03, self.inputAno04)
        Ventana_.setTabOrder(self.inputAno04, self.inputAno11)
        Ventana_.setTabOrder(self.inputAno11, self.inputAno12)
        Ventana_.setTabOrder(self.inputAno12, self.inputAno13)
        Ventana_.setTabOrder(self.inputAno13, self.inputAno14)
        Ventana_.setTabOrder(self.inputAno14, self.inputAno21)
        Ventana_.setTabOrder(self.inputAno21, self.inputAno22)
        Ventana_.setTabOrder(self.inputAno22, self.inputAno23)
        Ventana_.setTabOrder(self.inputAno23, self.inputAno24)
        Ventana_.setTabOrder(self.inputAno24, self.botonGrafico)

    def retranslateUi(self, Ventana_):
        _translate = QtCore.QCoreApplication.translate
        Ventana_.setWindowTitle(_translate("Ventana_", "IPC"))
        self.cajaAnos.setTitle(_translate("Ventana_", "Años"))
        self.inputAno2.setToolTip(_translate("Ventana_", "Dos Años"))
        self.inputAno2.setText(_translate("Ventana_", "2 Años"))
        self.cajaBienes.setTitle(_translate("Ventana_", "Bienes"))
        self.inputBienes4.setToolTip(_translate("Ventana_", "4 Bienes"))
        self.inputBienes4.setText(_translate("Ventana_", "4 Bienes"))
        self.inputBienes3.setToolTip(_translate("Ventana_", "3 Bienes"))
        self.inputBienes3.setText(_translate("Ventana_", "3 Bienes"))
        self.inputBienes2.setToolTip(_translate("Ventana_", "2 Bienes"))
        self.inputBienes2.setText(_translate("Ventana_", "2 Bienes"))
        self.inputBienes5.setToolTip(_translate("Ventana_", "5 Bienes"))
        self.inputBienes5.setText(_translate("Ventana_", "5 Bienes"))
        self.cajaPorcentajes.setTitle(_translate("Ventana_", "Porcentajes"))
        self.inputPorcentaje4.setToolTip(_translate("Ventana_", "Porcentaje"))
        self.inputPorcentaje4.setSuffix(_translate("Ventana_", "%"))
        self.inputPorcentaje3.setToolTip(_translate("Ventana_", "Porcentaje"))
        self.inputPorcentaje3.setSuffix(_translate("Ventana_", "%"))
        self.printPorcentaje3.setText(_translate("Ventana_", "% 3:"))
        self.printPorcentaje4.setText(_translate("Ventana_", "% 4:"))
        self.printPorcentaje1.setText(_translate("Ventana_", "% 1:"))
        self.inputPorcentaje1.setToolTip(_translate("Ventana_", "Porcentaje"))
        self.inputPorcentaje1.setSuffix(_translate("Ventana_", "%"))
        self.printPorcentaje2.setText(_translate("Ventana_", "% 2:"))
        self.inputPorcentaje2.setToolTip(_translate("Ventana_", "Porcentaje"))
        self.inputPorcentaje2.setSuffix(_translate("Ventana_", "%"))
        self.printPorcentaje5.setText(_translate("Ventana_", "% 5:"))
        self.inputPorcentaje5.setToolTip(_translate("Ventana_", "Porcentaje"))
        self.inputPorcentaje5.setSuffix(_translate("Ventana_", "%"))
        self.cajaGrafico.setTitle(_translate("Ventana_", "Grafico"))
        self.botonGrafico.setToolTip(_translate("Ventana_", "Generar Gráfica"))
        self.botonGrafico.setText(_translate("Ventana_", "Generar "))
        self.cajaDatos.setTitle(_translate("Ventana_", "Datos"))
        self.inputAno22.setToolTip(_translate("Ventana_", "Dato"))
        self.printAno12.setText(_translate("Ventana_", "Año 1-2:"))
        self.inputAno02.setToolTip(_translate("Ventana_", "Dato"))
        self.inputAno12.setToolTip(_translate("Ventana_", "Dato"))
        self.printAno22.setText(_translate("Ventana_", "Año 2-2:"))
        self.inputAno03.setToolTip(_translate("Ventana_", "Dato"))
        self.printAno03.setText(_translate("Ventana_", "Año base 3:"))
        self.inputAno23.setToolTip(_translate("Ventana_", "Dato"))
        self.printAno14.setText(_translate("Ventana_", "Año 1-4:"))
        self.inputAno04.setToolTip(_translate("Ventana_", "Dato"))
        self.printAno04.setText(_translate("Ventana_", "Año base 4:"))
        self.inputAno13.setToolTip(_translate("Ventana_", "Dato"))
        self.printAno13.setText(_translate("Ventana_", "Año 1-3:"))
        self.printAno23.setText(_translate("Ventana_", "Año 2-3:"))
        self.inputAno01.setToolTip(_translate("Ventana_", "Dato"))
        self.printAno11.setText(_translate("Ventana_", "Año 1-1:"))
        self.inputAno11.setToolTip(_translate("Ventana_", "Dato"))
        self.printAno21.setText(_translate("Ventana_", "Año 2-1: "))
        self.printAno01.setText(_translate("Ventana_", "Año base 1:"))
        self.inputAno21.setToolTip(_translate("Ventana_", "Dato"))
        self.printAno02.setText(_translate("Ventana_", "Año base 2:"))
        self.inputAno24.setToolTip(_translate("Ventana_", "Dato"))
        self.printAno24.setText(_translate("Ventana_", "Año 2-4:"))
        self.inputAno14.setToolTip(_translate("Ventana_", "Dato"))
        self.printAno05.setText(_translate("Ventana_", "Año base 5:"))
        self.inputAno05.setToolTip(_translate("Ventana_", "Dato"))
        self.printAno15.setText(_translate("Ventana_", "Año 1-5:"))
        self.inputAno15.setToolTip(_translate("Ventana_", "Dato"))
        self.printAno25.setText(_translate("Ventana_", "Año 2-5:"))
        self.inputAno25.setToolTip(_translate("Ventana_", "Dato"))
        self.widget.setToolTip(_translate("Ventana_", "Versión 1.0.1 Gracias Por Utilizarla"))
        self.label.setWhatsThis(_translate("Ventana_", "Versión 1.2.1 Gracias Por Utilizarla"))
        self.label.setText(_translate("Ventana_", "Version 1.2.1"))
